# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'bootstrap_sass_rails'
gem 'font-awesome-middleman'
gem 'jquery-middleman'
gem "middleman", "~>3.1.4"
gem "middleman-livereload", "~> 3.1.0"
gem "manhattan", github: "kohactive/manhattan", branch: "0-4-0"
gem "nokogiri"
gem "primordial", github: "johnkoht/primordial"

gem 'sqlite3', '~> 1.3.9'